# Generated by Django 5.1.7 on 2025-04-19 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Echocardiogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dicom_file', models.FileField(upload_to='media/dicom/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echocardiogram', to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='EcoFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media/frames/')),
                ('frame_index', models.PositiveIntegerField()),
                ('echocardiogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='api.echocardiogram')),
            ],
        ),
        migrations.CreateModel(
            name='EcoFrameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('is_calcified', models.BooleanField(blank=True, default=False)),
                ('confidence', models.FloatField(blank=True, default=0.0)),
                ('frame', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='api.ecoframe')),
            ],
        ),
    ]
