# Generated by Django 5.1.7 on 2025-04-21 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_echocardiogram_ecoframe_ecoframedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echocardiogram',
            name='dicom_file',
            field=models.FileField(upload_to='dicom/'),
        ),
        migrations.AlterField(
            model_name='echocardiogram',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echocardiograms', to='api.patient'),
        ),
        migrations.AlterField(
            model_name='ecoframe',
            name='image',
            field=models.FileField(upload_to='frames/'),
        ),
    ]
