# Generated by Django 5.1.7 on 2025-04-23 11:28

import api.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_echocardiogram_dicom_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecoframedata',
            name='frame',
        ),
        migrations.CreateModel(
            name='EchoFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=api.utils.frame_image_upload_path)),
                ('frame_index', models.PositiveIntegerField()),
                ('echocardiogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='api.echocardiogram')),
            ],
        ),
        migrations.CreateModel(
            name='EchoFrameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('is_calcified', models.BooleanField(blank=True, default=False)),
                ('confidence', models.FloatField(blank=True, default=0.0)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='api.echoframe')),
            ],
        ),
        migrations.DeleteModel(
            name='EcoFrame',
        ),
        migrations.DeleteModel(
            name='EcoFrameData',
        ),
    ]
