# Generated by Django 5.1.7 on 2025-04-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_echoframedata_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echoframedata',
            name='is_calcified',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
