# Generated by Django 5.2 on 2025-04-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_echoframedata_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="echoDicom",
            field=models.FileField(blank=True, null=True, upload_to="dicom/"),
        ),
    ]
