# Generated by Django 5.2 on 2025-04-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_patient_echodicom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="echocardiogram",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="echoDicom",
            field=models.FileField(blank=True, null=True, upload_to="dicom"),
        ),
    ]
