# Generated by Django 5.1.7 on 2025-05-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_echoframedata_is_calcified'),
        ('api', '0007_alter_echocardiogram_description_and_more'),
    ]

    operations = [
    ]
