# Generated by Django 5.1.7 on 2025-05-01 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20250501_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='echoDicom',
        ),
    ]
