# Generated by Django 5.1.7 on 2025-05-03 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_patient_echodicom'),
    ]

    operations = [
        migrations.AddField(
            model_name='echoframedata',
            name='is_annotation_ai',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='echoframedata',
            name='is_calcification_ai',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
