# Generated by Django 5.1.7 on 2025-05-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_echoframedata_is_annotation_ai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='echocardiogram',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
