# Generated by Django 5.1.7 on 2025-05-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_echocardiogram_status_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echocardiogram',
            name='status',
            field=models.CharField(choices=[('UNREVIEWED', 'Unreviewed'), ('IN_PROGRESS', 'In Progress'), ('EVALUATED', 'Evaluated')], default='UNREVIEWED', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('EVALUATED', 'Evaluated')], default='PENDING', max_length=20),
        ),
    ]
