# Generated by Django 5.1.7 on 2025-05-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_echocardiogram_status_alter_patient_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='echoframedata',
            old_name='is_annotation_ai',
            new_name='is_annotation_generated',
        ),
        migrations.RenameField(
            model_name='echoframedata',
            old_name='is_calcification_ai',
            new_name='is_calcification_generated',
        ),
    ]
