# Generated by Django 5.2.1 on 2025-05-30 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_patient_filefield_reportpdf'),
        ('api', '0013_rename_is_annotation_ai_echoframedata_is_annotation_generated_and_more'),
    ]

    operations = [
    ]
