# Generated by Django 5.1.7 on 2025-05-30 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_merge_20250530_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='fileField',
        ),
    ]
