# Generated by Django 5.1.7 on 2025-05-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_patient_filefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='has_report',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
