# Generated by Django 5.2.1 on 2025-08-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_patient_has_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="echocardiogram",
            name="status",
            field=models.CharField(
                choices=[
                    ("REVIEW_NEEDED", "Review Needed"),
                    ("IN_PROGRESS", "In Progress"),
                    ("EVALUATED", "Evaluated"),
                ],
                default="REVIEW_NEEDED",
                max_length=20,
            ),
        ),
    ]
