# Generated by Codex on 2026-04-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_objective_variable_schema_alignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportpdf',
            name='echocardiogram',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reports',
                to='api.echocardiogram',
            ),
        ),
        migrations.AddField(
            model_name='reportpdf',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportpdf',
            name='has_calcification',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportpdf',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reportpdf',
            name='objective_variable',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportpdf',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportpdf',
            name='report_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reportpdf',
            name='status',
            field=models.CharField(
                choices=[
                    ('AUTO_GENERATED', 'Auto Generated'),
                    ('USER_REVIEWED', 'User Reviewed'),
                    ('READY', 'Ready'),
                    ('FAILED', 'Failed'),
                ],
                default='AUTO_GENERATED',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='reportpdf',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reportpdf',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='reportpdf',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportpdf',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AddConstraint(
            model_name='reportpdf',
            constraint=models.UniqueConstraint(
                fields=('patient', 'doctor', 'echocardiogram'),
                name='unique_report_per_exam_and_doctor',
            ),
        ),
    ]
